-- Catalogue reconciliation: brands + models.
--
-- Why this file exists: 37 brand rows and 111 model rows were inserted into the
-- live database outside of migrations, and the original catalogue seed
-- (20260708155853_eee15b3e-964c-4476-83b3-795b9aeca655.sql) is incomplete. A
-- from-scratch replay therefore produced a catalogue the app cannot run on.
-- This migration is generated from the live tables and is the authoritative
-- catalogue: replaying it converges a fresh database onto production.
--
-- It is idempotent (upsert on the real keys: brands.slug, models(brand_slug, name))
-- and contains no DELETEs — the seeded set is a subset of live, so nothing extra
-- has to be removed, and destructive statements do not belong in the chain.
--
-- The brands_tier_allowed CHECK lives here rather than in
-- 20260903092238_ffc3bbf8-fac4-452a-88e3-fbbc870814c8.sql because at that point
-- in a fresh replay the seed still holds tier = 'premium' rows, so the
-- constraint aborted the chain. It is re-added at the bottom, after the
-- catalogue has been reconciled, and guarded so it is a no-op on production.

INSERT INTO public.brands (slug, name, category, tier) VALUES
  ('balenciaga', 'Balenciaga', 'bags', 'mid_market'),
  ('bottega-veneta', 'Bottega Veneta', 'bags', 'mid_market'),
  ('celine', 'Celine', 'bags', 'mid_market'),
  ('chanel', 'Chanel', 'bags', 'luxury_invest'),
  ('chloe', 'Chloé', 'bags', 'mid_market'),
  ('coach', 'Coach', 'bags', 'mid_market'),
  ('dior', 'Dior', 'bags', 'luxury_invest'),
  ('fendi', 'Fendi', 'bags', 'mid_market'),
  ('ferragamo', 'Salvatore Ferragamo', 'bags', 'mid_market'),
  ('furla', 'Furla', 'bags', 'mid_market'),
  ('givenchy', 'Givenchy', 'bags', 'mid_market'),
  ('goyard', 'Goyard', 'bags', 'luxury_invest'),
  ('gucci', 'Gucci', 'bags', 'mid_market'),
  ('hermes', 'Hermès', 'bags', 'luxury_invest'),
  ('kate-spade', 'Kate Spade', 'bags', 'mid_market'),
  ('loewe', 'Loewe', 'bags', 'mid_market'),
  ('longchamp', 'Longchamp', 'bags', 'mid_market'),
  ('louis-vuitton', 'Louis Vuitton', 'bags', 'luxury_invest'),
  ('marc-jacobs', 'Marc Jacobs', 'bags', 'mid_market'),
  ('michael-kors', 'Michael Kors', 'bags', 'mid_market'),
  ('miu-miu', 'Miu Miu', 'bags', 'mid_market'),
  ('mulberry', 'Mulberry', 'bags', 'mid_market'),
  ('prada', 'Prada', 'bags', 'mid_market'),
  ('saint-laurent', 'Saint Laurent', 'bags', 'mid_market'),
  ('tory-burch', 'Tory Burch', 'bags', 'mid_market'),
  ('valentino', 'Valentino', 'bags', 'mid_market'),
  ('boucheron', 'Boucheron', 'jewelry', 'luxury_invest'),
  ('buccellati', 'Buccellati', 'jewelry', 'luxury_invest'),
  ('bulgari', 'Bulgari', 'jewelry', 'luxury_invest'),
  ('cartier-jewelry', 'Cartier', 'jewelry', 'luxury_invest'),
  ('chaumet', 'Chaumet', 'jewelry', 'luxury_invest'),
  ('chopard', 'Chopard', 'jewelry', 'luxury_invest'),
  ('david-yurman', 'David Yurman', 'jewelry', 'mid_market'),
  ('faberge', 'Fabergé', 'jewelry', 'luxury_invest'),
  ('georg-jensen', 'Georg Jensen', 'jewelry', 'mid_market'),
  ('graff', 'Graff', 'jewelry', 'luxury_invest'),
  ('harry-winston', 'Harry Winston', 'jewelry', 'luxury_invest'),
  ('john-hardy', 'John Hardy', 'jewelry', 'mid_market'),
  ('marco-bicego', 'Marco Bicego', 'jewelry', 'mid_market'),
  ('mejuri', 'Mejuri', 'jewelry', 'mid_market'),
  ('messika', 'Messika', 'jewelry', 'mid_market'),
  ('mikimoto', 'Mikimoto', 'jewelry', 'luxury_invest'),
  ('monica-vinader', 'Monica Vinader', 'jewelry', 'mid_market'),
  ('piaget', 'Piaget', 'jewelry', 'luxury_invest'),
  ('pomellato', 'Pomellato', 'jewelry', 'luxury_invest'),
  ('roberto-coin', 'Roberto Coin', 'jewelry', 'mid_market'),
  ('tacori', 'Tacori', 'jewelry', 'mid_market'),
  ('tiffany', 'Tiffany & Co.', 'jewelry', 'luxury_invest'),
  ('van-cleef-arpels', 'Van Cleef & Arpels', 'jewelry', 'luxury_invest'),
  ('a-lange-sohne', 'A. Lange & Söhne', 'watches', 'luxury_invest'),
  ('audemars-piguet', 'Audemars Piguet', 'watches', 'luxury_invest'),
  ('baume-mercier', 'Baume & Mercier', 'watches', 'mid_market'),
  ('bell-ross', 'Bell & Ross', 'watches', 'mid_market'),
  ('blancpain', 'Blancpain', 'watches', 'luxury_invest'),
  ('breguet', 'Breguet', 'watches', 'luxury_invest'),
  ('breitling', 'Breitling', 'watches', 'mid_market'),
  ('cartier-watches', 'Cartier', 'watches', 'luxury_invest'),
  ('citizen', 'Citizen', 'watches', 'mid_market'),
  ('girard-perregaux', 'Girard-Perregaux', 'watches', 'luxury_invest'),
  ('grand-seiko', 'Grand Seiko', 'watches', 'mid_market'),
  ('hamilton', 'Hamilton', 'watches', 'mid_market'),
  ('hublot', 'Hublot', 'watches', 'luxury_invest'),
  ('iwc', 'IWC Schaffhausen', 'watches', 'luxury_invest'),
  ('jaeger-lecoultre', 'Jaeger-LeCoultre', 'watches', 'luxury_invest'),
  ('longines', 'Longines', 'watches', 'mid_market'),
  ('montblanc', 'Montblanc', 'watches', 'mid_market'),
  ('nomos', 'Nomos Glashütte', 'watches', 'mid_market'),
  ('omega', 'Omega', 'watches', 'luxury_invest'),
  ('orient', 'Orient', 'watches', 'mid_market'),
  ('oris', 'Oris', 'watches', 'mid_market'),
  ('panerai', 'Panerai', 'watches', 'luxury_invest'),
  ('patek-philippe', 'Patek Philippe', 'watches', 'luxury_invest'),
  ('rado', 'Rado', 'watches', 'mid_market'),
  ('richard-mille', 'Richard Mille', 'watches', 'luxury_invest'),
  ('rolex', 'Rolex', 'watches', 'luxury_invest'),
  ('seiko', 'Seiko', 'watches', 'mid_market'),
  ('tag-heuer', 'TAG Heuer', 'watches', 'mid_market'),
  ('tissot', 'Tissot', 'watches', 'mid_market'),
  ('tudor', 'Tudor', 'watches', 'mid_market'),
  ('ulysse-nardin', 'Ulysse Nardin', 'watches', 'luxury_invest'),
  ('vacheron-constantin', 'Vacheron Constantin', 'watches', 'luxury_invest'),
  ('zenith', 'Zenith', 'watches', 'luxury_invest')
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, tier = EXCLUDED.tier;

-- models: upsert on the UNIQUE (brand_slug, name) constraint (models_brand_slug_name_key).
-- id is a generated uuid and is intentionally not pinned.
INSERT INTO public.models (brand_slug, name) VALUES
  ('a-lange-sohne', 'Lange 1'),
  ('a-lange-sohne', 'Odysseus'),
  ('a-lange-sohne', 'Saxonia'),
  ('a-lange-sohne', 'Zeitwerk'),
  ('audemars-piguet', 'Code 11.59'),
  ('audemars-piguet', 'Millenary'),
  ('audemars-piguet', 'Royal Oak'),
  ('audemars-piguet', 'Royal Oak Offshore'),
  ('balenciaga', 'City'),
  ('balenciaga', 'Hourglass'),
  ('balenciaga', 'Le Cagole'),
  ('baume-mercier', 'Classima'),
  ('baume-mercier', 'Clifton'),
  ('baume-mercier', 'Riviera'),
  ('bell-ross', 'BR 03'),
  ('bell-ross', 'BR 05'),
  ('bell-ross', 'BR V2'),
  ('blancpain', 'Air Command'),
  ('blancpain', 'Bathyscaphe'),
  ('blancpain', 'Fifty Fathoms'),
  ('blancpain', 'Villeret'),
  ('bottega-veneta', 'Andiamo'),
  ('bottega-veneta', 'Arco'),
  ('bottega-veneta', 'Cassette'),
  ('bottega-veneta', 'Jodie'),
  ('boucheron', 'Jack de Boucheron'),
  ('boucheron', 'Quatre'),
  ('boucheron', 'Serpent Bohème'),
  ('breguet', 'Classique'),
  ('breguet', 'Marine'),
  ('breguet', 'Tradition'),
  ('breguet', 'Type XX'),
  ('breitling', 'Avenger'),
  ('breitling', 'Chronomat'),
  ('breitling', 'Navitimer'),
  ('breitling', 'Superocean'),
  ('buccellati', 'Blossoms'),
  ('buccellati', 'Macri'),
  ('buccellati', 'Opera'),
  ('bulgari', 'B.zero1'),
  ('bulgari', 'Bulgari Bulgari'),
  ('bulgari', 'Divas'' Dream'),
  ('bulgari', 'Serpenti'),
  ('cartier-jewelry', 'Clash de Cartier'),
  ('cartier-jewelry', 'Juste un Clou'),
  ('cartier-jewelry', 'Love Bracelet'),
  ('cartier-jewelry', 'Panthère de Cartier'),
  ('cartier-jewelry', 'Trinity'),
  ('cartier-watches', 'Baignoire'),
  ('cartier-watches', 'Ballon Bleu'),
  ('cartier-watches', 'Panthère'),
  ('cartier-watches', 'Santos'),
  ('cartier-watches', 'Tank'),
  ('celine', 'Belt Bag'),
  ('celine', 'Luggage'),
  ('celine', 'Triomphe'),
  ('chanel', '19 Bag'),
  ('chanel', '2.55 Reissue'),
  ('chanel', 'Boy Bag'),
  ('chanel', 'Classic Flap'),
  ('chaumet', 'Bee My Love'),
  ('chaumet', 'Joséphine'),
  ('chaumet', 'Liens'),
  ('chloe', 'Marcie'),
  ('chloe', 'Paddington'),
  ('chloe', 'Woody'),
  ('chopard', 'Happy Diamonds'),
  ('chopard', 'Happy Hearts'),
  ('chopard', 'Ice Cube'),
  ('chopard', 'L''Heure du Diamant'),
  ('citizen', 'Eco-Drive'),
  ('citizen', 'Promaster'),
  ('citizen', 'Tsuyosa'),
  ('coach', 'Rogue'),
  ('coach', 'Tabby'),
  ('coach', 'Willow'),
  ('david-yurman', 'Cable Bracelet'),
  ('david-yurman', 'Cable Classics'),
  ('david-yurman', 'Petite Pavé'),
  ('dior', 'Book Tote'),
  ('dior', 'Caro'),
  ('dior', 'Lady Dior'),
  ('dior', 'Saddle'),
  ('faberge', 'Colours of Love'),
  ('faberge', 'Egg Pendant'),
  ('fendi', 'Baguette'),
  ('fendi', 'Peekaboo'),
  ('fendi', 'Sunshine'),
  ('ferragamo', 'Gancini'),
  ('ferragamo', 'Hug'),
  ('ferragamo', 'Studio'),
  ('furla', '1927'),
  ('furla', 'Metropolis'),
  ('georg-jensen', 'Fusion'),
  ('georg-jensen', 'Halo'),
  ('georg-jensen', 'Offspring'),
  ('girard-perregaux', 'Constant Escapement'),
  ('girard-perregaux', 'Laureato'),
  ('girard-perregaux', 'Vintage 1945'),
  ('givenchy', '4G'),
  ('givenchy', 'Antigona'),
  ('givenchy', 'Voyou'),
  ('goyard', 'Anjou'),
  ('goyard', 'Artois'),
  ('goyard', 'Saint Louis'),
  ('graff', 'Butterfly'),
  ('graff', 'Gyre'),
  ('graff', 'Spiral'),
  ('grand-seiko', 'Heritage'),
  ('grand-seiko', 'Snowflake'),
  ('grand-seiko', 'Spring Drive'),
  ('gucci', 'Bamboo 1947'),
  ('gucci', 'Dionysus'),
  ('gucci', 'GG Marmont'),
  ('gucci', 'Jackie 1961'),
  ('hamilton', 'Jazzmaster'),
  ('hamilton', 'Khaki Field'),
  ('hamilton', 'Ventura'),
  ('harry-winston', 'Lily Cluster'),
  ('harry-winston', 'Sunflower'),
  ('harry-winston', 'Winston Cluster'),
  ('hermes', 'Birkin'),
  ('hermes', 'Constance'),
  ('hermes', 'Garden Party'),
  ('hermes', 'Kelly'),
  ('hermes', 'Lindy'),
  ('hublot', 'Big Bang'),
  ('hublot', 'Classic Fusion'),
  ('hublot', 'Spirit of Big Bang'),
  ('iwc', 'Aquatimer'),
  ('iwc', 'Ingenieur'),
  ('iwc', 'Pilot''s Watch'),
  ('iwc', 'Portofino'),
  ('iwc', 'Portugieser'),
  ('jaeger-lecoultre', 'Master Control'),
  ('jaeger-lecoultre', 'Master Ultra Thin'),
  ('jaeger-lecoultre', 'Polaris'),
  ('jaeger-lecoultre', 'Reverso'),
  ('john-hardy', 'Classic Chain'),
  ('john-hardy', 'Legends'),
  ('john-hardy', 'Naga'),
  ('kate-spade', 'Knott'),
  ('kate-spade', 'Sam'),
  ('loewe', 'Flamenco'),
  ('loewe', 'Hammock'),
  ('loewe', 'Puzzle'),
  ('longchamp', 'Le Pliage'),
  ('longchamp', 'Roseau'),
  ('longines', 'DolceVita'),
  ('longines', 'HydroConquest'),
  ('longines', 'Master Collection'),
  ('longines', 'Spirit'),
  ('louis-vuitton', 'Alma'),
  ('louis-vuitton', 'Capucines'),
  ('louis-vuitton', 'Neverfull'),
  ('louis-vuitton', 'OnTheGo'),
  ('louis-vuitton', 'Speedy'),
  ('marc-jacobs', 'Snapshot'),
  ('marc-jacobs', 'The Tote Bag'),
  ('marco-bicego', 'Africa'),
  ('marco-bicego', 'Jaipur'),
  ('marco-bicego', 'Lunaria'),
  ('mejuri', 'Bold Hoops'),
  ('mejuri', 'Croissant Dôme'),
  ('messika', 'Lucky Move'),
  ('messika', 'Move'),
  ('messika', 'So Move'),
  ('michael-kors', 'Hamilton'),
  ('michael-kors', 'Jet Set'),
  ('mikimoto', 'Akoya Pearl Strand'),
  ('mikimoto', 'Pearl Stud Earrings'),
  ('miu-miu', 'Arcadie'),
  ('miu-miu', 'Matelassé'),
  ('miu-miu', 'Wander'),
  ('monica-vinader', 'Fiji'),
  ('monica-vinader', 'Nura'),
  ('monica-vinader', 'Siren'),
  ('montblanc', '1858'),
  ('montblanc', 'Heritage'),
  ('montblanc', 'Star Legacy'),
  ('mulberry', 'Alexa'),
  ('mulberry', 'Bayswater'),
  ('mulberry', 'Lily'),
  ('nomos', 'Club'),
  ('nomos', 'Metro'),
  ('nomos', 'Orion'),
  ('nomos', 'Tangente'),
  ('omega', 'Aqua Terra'),
  ('omega', 'Constellation'),
  ('omega', 'De Ville'),
  ('omega', 'Seamaster'),
  ('omega', 'Speedmaster'),
  ('orient', 'Bambino'),
  ('orient', 'Kamasu'),
  ('oris', 'Aquis'),
  ('oris', 'Big Crown'),
  ('oris', 'Divers Sixty-Five'),
  ('panerai', 'Luminor'),
  ('panerai', 'Radiomir'),
  ('panerai', 'Submersible'),
  ('patek-philippe', 'Aquanaut'),
  ('patek-philippe', 'Calatrava'),
  ('patek-philippe', 'Gondolo'),
  ('patek-philippe', 'Grand Complications'),
  ('patek-philippe', 'Nautilus'),
  ('patek-philippe', 'Twenty-4'),
  ('piaget', 'Altiplano'),
  ('piaget', 'Limelight'),
  ('piaget', 'Possession'),
  ('pomellato', 'Iconica'),
  ('pomellato', 'Nudo'),
  ('pomellato', 'Sabbia'),
  ('prada', 'Cleo'),
  ('prada', 'Galleria'),
  ('prada', 'Re-Edition'),
  ('rado', 'Captain Cook'),
  ('rado', 'DiaMaster'),
  ('rado', 'True'),
  ('richard-mille', 'RM 011'),
  ('richard-mille', 'RM 035'),
  ('richard-mille', 'RM 055'),
  ('richard-mille', 'RM 07-01'),
  ('roberto-coin', 'Love in Verona'),
  ('roberto-coin', 'Tiny Treasures'),
  ('roberto-coin', 'Venetian Princess'),
  ('rolex', 'Datejust'),
  ('rolex', 'Day-Date'),
  ('rolex', 'Daytona'),
  ('rolex', 'Explorer'),
  ('rolex', 'GMT-Master II'),
  ('rolex', 'Oyster Perpetual'),
  ('rolex', 'Sea-Dweller'),
  ('rolex', 'Sky-Dweller'),
  ('rolex', 'Submariner'),
  ('rolex', 'Yacht-Master'),
  ('saint-laurent', 'Kate'),
  ('saint-laurent', 'Loulou'),
  ('saint-laurent', 'Sac de Jour'),
  ('seiko', '5 Sports'),
  ('seiko', 'Presage'),
  ('seiko', 'Prospex'),
  ('tacori', 'Dantela'),
  ('tacori', 'Sculpted Crescent'),
  ('tag-heuer', 'Aquaracer'),
  ('tag-heuer', 'Carrera'),
  ('tag-heuer', 'Formula 1'),
  ('tag-heuer', 'Monaco'),
  ('tiffany', 'Return to Tiffany'),
  ('tiffany', 'Tiffany HardWear'),
  ('tiffany', 'Tiffany Lock'),
  ('tiffany', 'Tiffany Setting'),
  ('tiffany', 'Tiffany T'),
  ('tiffany', 'Victoria'),
  ('tissot', 'Gentleman'),
  ('tissot', 'Le Locle'),
  ('tissot', 'PRX'),
  ('tissot', 'Seastar'),
  ('tory-burch', 'Kira'),
  ('tory-burch', 'Lee Radziwill'),
  ('tory-burch', 'Robinson'),
  ('tudor', 'Black Bay'),
  ('tudor', 'Pelagos'),
  ('tudor', 'Ranger'),
  ('tudor', 'Royal'),
  ('ulysse-nardin', 'Blast'),
  ('ulysse-nardin', 'Diver'),
  ('ulysse-nardin', 'Freak'),
  ('ulysse-nardin', 'Marine'),
  ('vacheron-constantin', 'Historiques'),
  ('vacheron-constantin', 'Overseas'),
  ('vacheron-constantin', 'Patrimony'),
  ('vacheron-constantin', 'Traditionnelle'),
  ('valentino', 'Rockstud'),
  ('valentino', 'Roman Stud'),
  ('valentino', 'VLogo'),
  ('van-cleef-arpels', 'Alhambra'),
  ('van-cleef-arpels', 'Frivole'),
  ('van-cleef-arpels', 'Lucky Spring'),
  ('van-cleef-arpels', 'Perlée'),
  ('van-cleef-arpels', 'Two Butterfly'),
  ('zenith', 'Chronomaster'),
  ('zenith', 'Defy'),
  ('zenith', 'El Primero'),
  ('zenith', 'Pilot')
ON CONFLICT (brand_slug, name) DO NOTHING;

-- Re-add the tier constraint, guarded: production already has it, a fresh
-- database does not.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'brands_tier_allowed'
  ) THEN
    ALTER TABLE public.brands ADD CONSTRAINT brands_tier_allowed
      CHECK (tier IN ('luxury_invest','mid_market'));
  END IF;
END $$;
